# Generated by Django 4.2.9 on 2024-02-13 15:26

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0017_image__transparent'),
        ('news', '0006_alter_photopost_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на внешнее видео')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.post')),
                ('videofile', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.file', verbose_name='Видеофайл')),
            ],
            options={
                'verbose_name': 'Вилео',
                'verbose_name_plural': 'Видео',
                'ordering': ['-created_at'],
            },
        ),
    ]
