# Generated by Django 4.2.9 on 2024-02-14 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_videopost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videopost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
    ]
