# Generated by Django 4.2.9 on 2025-06-03 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_videopost_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsplugin',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.postcategory', verbose_name='Категория'),
        ),
    ]
