# Generated by Django 4.2.9 on 2025-06-11 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_attachments_attachment_plugin'),
        ('news', '0009_newsplugin_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentPost',
            fields=[
                ('attachment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attachments.attachment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.post')),
            ],
            bases=('attachments.attachment',),
        ),
    ]
