# Generated by Django 4.2.9 on 2025-06-11 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_attachmentpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachmentpost',
            options={'ordering': ['-updated_at'], 'verbose_name': 'вложение', 'verbose_name_plural': 'вложения'},
        ),
    ]
