# Generated by Django 4.2.9 on 2025-06-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_attachmentpost_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsplugin',
            name='layout',
            field=models.CharField(choices=[('Блоки', 'blocks'), ('Список', 'list')], default='Блоки', max_length=16, verbose_name='Макет отображения'),
        ),
    ]
