# Generated by Django 4.2.9 on 2025-06-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_newsplugin_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsplugin',
            name='layout',
            field=models.CharField(choices=[('blocks', 'Блоки'), ('list', 'Список')], default='blocks', max_length=16, verbose_name='Макет отображения'),
        ),
    ]
