# Generated by Django 4.2.9 on 2025-06-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_alter_newsplugin_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsplugin',
            name='bootstrap_col',
            field=models.CharField(choices=[('12', 1), ('6', 2), ('4', 3)], default='4', max_length=8, verbose_name='Количество блоков в строке'),
        ),
    ]
