# Generated by Django 4.2.9 on 2025-06-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_newsplugin_bootstrap_col'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsplugin',
            name='show_borders',
            field=models.BooleanField(default=True, verbose_name='Отображать границу блоков'),
        ),
    ]
