# Generated by Django 4.2.9 on 2025-06-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_newsplugin_show_borders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsplugin',
            name='show_borders',
        ),
        migrations.AddField(
            model_name='newsplugin',
            name='hide_borders',
            field=models.BooleanField(default=False, verbose_name='Скрыть границу блоков'),
        ),
    ]
