# Generated by Django 4.2.9 on 2025-05-26 09:32

from django.db import migrations, models
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_alter_contactsettings_agreement_checkbox_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsettings',
            name='verification_form_text',
            field=djangocms_text_ckeditor.fields.HTMLField(default='', verbose_name='Текст на форме с кодом подтверждения'),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='verification_form_title',
            field=models.CharField(default='Подтвердите данные', max_length=256, verbose_name='Название этапа заполнения обращение'),
        ),
    ]
