# Generated by Django 4.2.9 on 2025-05-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0012_contactsettings_verification_form_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsettings',
            name='verification_form_title',
            field=models.CharField(default='Подтвердите данные', max_length=256, verbose_name='Название этапа с подтверждением кодом'),
        ),
    ]
