# Generated by Django 4.2.9 on 2025-07-02 07:46

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('layout', models.CharField(choices=[('bottom-right', 'Справа внизу'), ('top-left', 'Слева вверху'), ('top-right', 'Справа вверху'), ('bottom-left', 'Слева внизу'), ('bottom', 'Внизу во всю ширину'), ('top', 'Вверху во всю ширину')], default='bottom-right', max_length=32, verbose_name='Расположение')),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='Заголовок')),
                ('content', djangocms_text_ckeditor.fields.HTMLField(verbose_name='Содержимое')),
                ('use_button', models.BooleanField(default=True, verbose_name='Использовать кнопку')),
                ('button_text', models.CharField(default='Хорошо', max_length=64, verbose_name='Текст кнопки')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
