# Generated by Django 4.2.9 on 2025-05-19 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0035_documentsplugin_num_objects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(default='Решение', help_text='Примеры: "Постановление" , "Уставной документ", и т.д.   Номер и дату в этом поле не указывайте', max_length=512, verbose_name='Название документа'),
        ),
    ]
