# Generated by Django 4.2.9 on 2025-05-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0036_alter_document_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='place_publication',
            field=models.CharField(blank=True, help_text='Пример: газета "Шахтерская правда" №69', max_length=256, null=True, verbose_name='Место публикации'),
        ),
    ]
