# Generated by Django 4.2.9 on 2025-05-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0037_document_place_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='cancel_docs',
            field=models.ManyToManyField(to='docs.document', verbose_name='Отменяемые документы'),
        ),
        migrations.AddField(
            model_name='document',
            name='change_docs',
            field=models.ManyToManyField(to='docs.document', verbose_name='Изменяемые документы'),
        ),
    ]
