# Generated by Django 4.2.9 on 2025-05-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0038_document_cancel_docs_document_change_docs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='cancel_docs',
            field=models.ManyToManyField(blank=True, null=True, to='docs.document', verbose_name='Отменяемые документы'),
        ),
        migrations.AlterField(
            model_name='document',
            name='change_docs',
            field=models.ManyToManyField(blank=True, null=True, to='docs.document', verbose_name='Изменяемые документы'),
        ),
    ]
