# Generated by Django 4.2.9 on 2025-05-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0039_alter_document_cancel_docs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='cancel_docs',
            field=models.ManyToManyField(blank=True, null=True, related_name='cancel_documents', to='docs.document', verbose_name='Отменяемые документы'),
        ),
        migrations.AlterField(
            model_name='document',
            name='change_docs',
            field=models.ManyToManyField(blank=True, null=True, related_name='change_documents', to='docs.document', verbose_name='Изменяемые документы'),
        ),
    ]
