# Generated by Django 4.2.9 on 2025-05-21 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0041_remove_document_cancel_docs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='cancel_docs',
            field=models.ManyToManyField(blank=True, to='docs.document', verbose_name='Отменяемые документы'),
        ),
        migrations.CreateModel(
            name='ChangeRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_doc', to='docs.document')),
                ('target_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_doc', to='docs.document')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='change_docs',
            field=models.ManyToManyField(blank=True, through='docs.ChangeRelation', to='docs.document', verbose_name='Изменяемые документы'),
        ),
    ]
