# Generated by Django 4.2.9 on 2025-05-21 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0042_document_cancel_docs_changerelation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='change_docs',
        ),
    ]
