# Generated by Django 4.2.9 on 2025-05-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0043_remove_document_change_docs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='cancel_docs',
            field=models.ManyToManyField(blank=True, related_name='cancel_doc', to='docs.document', verbose_name='Отменяемые документы'),
        ),
    ]
