# Generated by Django 4.2.9 on 2025-05-21 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0045_alter_document_cancel_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='change_docs',
            field=models.ManyToManyField(blank=True, related_name='changed_by_docs', to='docs.document', verbose_name='Изменяемые документы'),
        ),
        migrations.AlterField(
            model_name='document',
            name='cancel_docs',
            field=models.ManyToManyField(blank=True, related_name='canceled_by_docs', to='docs.document', verbose_name='Отменяемые документы'),
        ),
        migrations.DeleteModel(
            name='ChangeRelation',
        ),
    ]
