# Generated by Django 4.2.9 on 2025-06-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0046_document_change_docs_alter_document_cancel_docs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='changed_by',
            field=models.CharField(blank=True, max_length=2056, null=True, verbose_name='Изменено (ТОЛЬКО ДЛЯ ИМПОРТА СТАРЫХ ДАННЫХ)'),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(default='Решение', help_text='Примеры: "Постановление" , "Уставной документ", и т.д.   Номер и дату в этом поле не указывайте', max_length=2056, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='subname',
            field=models.CharField(blank=True, help_text='Без внешних кавычек. Пример: Об утверждении правил перевозки детей. ', max_length=2056, null=True, verbose_name='Описание документа'),
        ),
    ]
