# Generated by Django 4.2.9 on 2025-06-25 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0047_document_changed_by_alter_document_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-published_at', '-number'], 'verbose_name': 'документ', 'verbose_name_plural': 'документы'},
        ),
    ]
