# Generated by Django 4.2.9 on 2025-07-02 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccordionPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('speed', models.PositiveSmallIntegerField(default=1000, verbose_name='Скорость раскрытия (мс)')),
                ('close_others', models.BooleanField(default=True, verbose_name='Закрывать другие вкладки при открытии')),
                ('auto_open', models.BooleanField(default=True, verbose_name='Автоматически открывать вкладку при загрузке')),
                ('num_auto_open', models.PositiveSmallIntegerField(default=1, verbose_name='Номер вкладки')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='HeaderPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(default=' ', max_length=1024, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Подзаголовок (не обязательно)')),
                ('layout', models.CharField(choices=[('bold-line', 'С жирной линией'), ('thin-line', 'С тонкой линией'), ('no-line', 'Без линии')], default='bold-line', max_length=32, verbose_name='Стиль')),
                ('align', models.CharField(choices=[('left', 'Слева'), ('center', 'По центру'), ('right', 'Справа')], default='left', max_length=32, verbose_name='Выравнивание')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ItemAccordionPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('name', models.CharField(max_length=2056, verbose_name='Название')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ItemArticlePlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('name', models.CharField(max_length=2056, verbose_name='Название')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='PureCodePlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('code', models.TextField(blank=True, help_text='Использовать js и css здесь возможно, но не рекомендуется.', null=True, verbose_name='HTML')),
                ('css', models.TextField(blank=True, null=True, verbose_name='CSS')),
                ('js', models.TextField(blank=True, help_text='Доступно использование jQuery, пример "$(document).ready(function () {                           alert("test");});"', null=True, verbose_name='JAVASCRIPT')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=256, verbose_name='Заголовок')),
                ('subtitle', models.CharField(default='', max_length=256, verbose_name='Подзаголовок')),
                ('phone', models.CharField(default='', max_length=256, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('address', models.CharField(default='', max_length=256, verbose_name='Адрес')),
                ('share_vk', models.BooleanField(default=True, verbose_name='Вконтакте')),
                ('share_ok', models.BooleanField(default=True, verbose_name='Одноклассники')),
                ('share_fb', models.BooleanField(default=False, verbose_name='Facebook')),
                ('share_twitter', models.BooleanField(default=True, verbose_name='Twitter')),
                ('menu_style', models.CharField(choices=[('1', 'Стиль №1'), ('2', 'Стиль №2')], default='1', max_length=10, verbose_name='Макет главного меню')),
                ('logo', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Конфигурация сайта',
                'verbose_name_plural': 'Конфигурация сайта',
            },
        ),
        migrations.CreateModel(
            name='SubmenuPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('layout', models.CharField(choices=[('blocks', 'Блоки'), ('list', 'Список')], default='blocks', max_length=32, verbose_name='Макет')),
                ('parent_page', models.CharField(blank=True, help_text='Указывается идентификатор страницы, дочернее меню которой будет отображено.                                 (ID заполняется в расширенных настройках страницы). Если не указано, будет отображено                                 дочернее меню текущей страницы', max_length=32, null=True, verbose_name='ID родителя (не обязательно)')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='TabPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='TabsPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('justified', models.BooleanField(default=True, verbose_name='Растянуть строку переключателей вкладок во всю ширину')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='WhitespacePlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('size', models.CharField(choices=[('medium', 'Средне'), ('small', 'Чуть чуть'), ('large', 'Побольше')], default='medium', max_length=32, verbose_name='Размер')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', help_text='Примеры: "ВК", "Мы в контакте", "Мы в ВК"', max_length=256, verbose_name='Текст')),
                ('url', models.URLField(verbose_name='Ссылка на страницу в соц.сети.')),
                ('icon', models.CharField(default='', help_text='Названия иконок брать <a href="https://fontawesome.com/v4/icons/" target="blank">отсюда</a>', max_length=32, verbose_name='Иконка соц.сети')),
                ('sitesettings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sitesettings')),
            ],
            options={
                'verbose_name': 'соц.сеть',
                'verbose_name_plural': 'соц.сети',
            },
        ),
        migrations.CreateModel(
            name='MenuItemSettingsExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa_icon', models.CharField(blank=True, default='', help_text='Названия иконок брать <a href="https://fontawesome.com/v4/icons/" target="blank">отсюда</a>', max_length=32, verbose_name='Иконка пункта меню')),
                ('dropdown_mega', models.BooleanField(default=False, help_text='Если отмечено, выпадающее меню будет во всю ширину                                         (работает только на верхнем уровне)', verbose_name='Mega Dropdown')),
                ('extended_object', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
                ('public_extension', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_extension', to='core.menuitemsettingsextension')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
