# Generated by Django 4.2.9 on 2025-06-03 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_itemarticleplugin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemaccordionplugin',
            name='name',
            field=models.CharField(max_length=2056, verbose_name='Название'),
        ),
    ]
