# Generated by Django 4.2.9 on 2025-06-03 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_itemaccordionplugin_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemarticleplugin',
            name='name',
            field=models.CharField(max_length=2056, verbose_name='Название'),
        ),
    ]
