# Generated by Django 4.2.9 on 2025-07-02 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sozyv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, help_text='Если оставить равным 0 - добавится в конец.', null=True, verbose_name='Порядок')),
                ('name', models.CharField(help_text='Пример: Созыв 3', max_length=256, verbose_name='Название')),
                ('period', models.CharField(blank=True, help_text='Пример: 04.2003 - 10.2008', max_length=256, null=True, verbose_name='Период')),
            ],
            options={
                'verbose_name': 'созыв',
                'verbose_name_plural': 'созывы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Deputat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, help_text='Если оставить равным 0 - добавится в конец.', null=True, verbose_name='Порядок')),
                ('lastname', models.CharField(max_length=128, verbose_name='Фамилия')),
                ('firstname', models.CharField(max_length=128, verbose_name='Имя')),
                ('surname', models.CharField(max_length=128, verbose_name='Отчество')),
                ('description', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='Описание')),
                ('photo', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='Фото')),
                ('sozyvy', models.ManyToManyField(to='deputaty.sozyv', verbose_name='Созыв')),
            ],
            options={
                'verbose_name': 'депутат',
                'verbose_name_plural': 'депутаты',
                'ordering': ['lastname', 'order'],
            },
        ),
    ]
