# Generated by Django 4.2.9 on 2025-05-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deputaty', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sozyv',
            options={'ordering': ['order'], 'verbose_name': 'созыв', 'verbose_name_plural': 'созывы'},
        ),
        migrations.AddField(
            model_name='sozyv',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Если оставить равным 0 - добавится в конец.', null=True, verbose_name='Порядок'),
        ),
    ]
