# Generated by Django 4.1.13 on 2025-07-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deputaty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, help_text='Если оставить равным 0 - добавится в конец.', null=True, verbose_name='Порядок')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'фракция',
                'verbose_name_plural': 'фракции',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='deputat',
            name='fractions',
            field=models.ManyToManyField(to='deputaty.fraction', verbose_name='Фракции'),
        ),
    ]
