# Generated by Django 4.2.9 on 2025-05-12 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deputaty', '0002_alter_sozyv_options_sozyv_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deputat',
            options={'ordering': ['lastname', 'order'], 'verbose_name': 'депутат', 'verbose_name_plural': 'депутаты'},
        ),
        migrations.RemoveField(
            model_name='deputat',
            name='sozyv',
        ),
        migrations.AddField(
            model_name='deputat',
            name='sozyvy',
            field=models.ManyToManyField(to='deputaty.sozyv', verbose_name='Созыв'),
        ),
    ]
