# Generated by Django 4.1.13 on 2025-07-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deputaty', '0002_fraction_deputat_fractions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deputat',
            name='fractions',
            field=models.ManyToManyField(blank=True, to='deputaty.fraction', verbose_name='Фракции'),
        ),
    ]
