# Generated by Django 4.2.9 on 2025-05-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deputaty', '0003_alter_deputat_options_remove_deputat_sozyv_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sozyv',
            options={'ordering': ['-order'], 'verbose_name': 'созыв', 'verbose_name_plural': 'созывы'},
        ),
        migrations.AddField(
            model_name='sozyv',
            name='period',
            field=models.CharField(blank=True, help_text='Пример: 04.2003 - 10.2008', null=True, verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='sozyv',
            name='name',
            field=models.CharField(help_text='Пример: Созыв 3', verbose_name='Название'),
        ),
    ]
