# Generated by Django 4.2.9 on 2025-05-19 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deputaty', '0004_alter_sozyv_options_sozyv_period_alter_sozyv_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sozyv',
            options={'ordering': ['order'], 'verbose_name': 'созыв', 'verbose_name_plural': 'созывы'},
        ),
    ]
